name: Deployment

on:
  workflow_dispatch:
    inputs:
      LZ:
         description: 'LZ Environment'
         required: true
         type: choice
         default: "dev"
         options:
         - "dev"
         - "production"
         - "nonexist"

      
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.LZ }}
    steps:
      - name: deploy
        run: echo "hello all"      
