name: hello world

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: get current date
      id: date
      run: echo "::set-output name=date::$(date +'%s')"
    - name: Build the Docker image
      run: echo "${{ steps.date.outputs.date }}"
    - name: print hello
      run: echo "Hello world!"
