name: in-workflow-j2j-output-reuse

on:
  push:
    branches:
      - main

jobs:
  generate_name:
    runs-on: ubuntu-latest
    outputs:
      random_name: ${{ steps.generate.outputs.test }}
    steps:
      - name: Generate Random Name
        id: generate
        run: echo "test=vijay" >> $GITHUB_OUTPUT

  print_name:
    runs-on: ubuntu-latest
    needs: generate_name
    steps:
      - name: Print Random Name
        run: | 
           echo "Random Name is -  ${{ needs.generate_name.outputs.random_name }}"
           echo "${{ needs.generate_name.outputs.random_name }}"
