name: matrix-example
on: workflow_dispatch
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: mylab-vm
    steps:
      - name: first step
        run: echo "Hello world"
      - name: second step
        run: echo " hello for-${{ matrix.os }}"
