name: matrix-example
on: workflow_dispatch
jobs:
  build:
    strategy:
      matrix:
        SA: 
          - 'dev/lz'
          - 'uat/lz'
          - 'prd/ls'
        ENV:
          - 'dev-de'
          - 'dev-in'
          - 'uat-in'
          - 'prd-de'
    runs-on: mylab-vm
    steps:
      - name: first step
        run: echo ${{ metrix.ENV }}
