name: matrix-example
on: workflow_dispatch
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: first step
        run: echo "Hello world"
