name: Call a reusable

on:
  workflow_dispatch:

jobs:
  ijob:
    uses: mevijays/test-actions/.github/workflows/workflow1.yml@main

  job2:
    uses: mevijays/test-actions/.github/workflows/workflow2.yml@main
    needs: ijob
    with:
       msg1: ${{ needs.ijob.outputs.msgout }}
       msg2: 'My system'
