name: Call a reusable

on:
  workflow_dispatch:

jobs:
  job1:
    uses: mevijays/test-actions/.github/workflows/workflow1.yml@main

  job2:
    uses: mevijays/test-actions/.github/workflows/workflow2.yml@main
    needs: job1
    with:
       msg1: ${{ needs.job1.outputs.output1 }}
       msg2: 'My system'
