name: "test reusable"
on: workflow_dispatch
jobs:
  mavenbuild:
    name: maven build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
  setup_java:
     uses: sharmavijay86/workflows/.github/workflows/build.yaml@main
     with:
       JAVA_VER: '11'
