name: Call workflow
on:
  workflow_dispatch:
    inputs:
      java_version:
        description: 'Select Java Version'
        required: true
        default: '8'
        options:
          - '8'
          - '11'
jobs:
  Call_reusable_workflow:
      uses: mevijays/workflows/.github/workflows/build.yaml@main
      with:
        java_version: ${{ inputs.java_version }}
