name: Call workflow
on:
  workflow_dispatch:
    inputs:
      java_version:
        description: 'Select Java Version'
        required: true
        default: '8'
        options:
          - '8'
          - '11'
jobs:
  call_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Call reusable workflow
        uses: ./workflow_dispatch
        with:
          java_version: ${{ github.event.inputs.java_version }}
