name: Call workflow
permissions:
  contents: read
  id-token: write
on:
  workflow_dispatch:
jobs:
  Call_reusable_workflow:
      uses: mevijays/vijay-work/.github/workflows/build.yaml@v1
      with:
        java_version: 8
