name: "test npm action"

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: [self-hosted, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: test env
        run: env
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm test
