name: Validate Ticket ID
on: 
 workflow_dispatch:
   inputs:
     ticket_id:
       required: true
       description: Ticket ID to validate
       default: "CHG1234567891"
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate ticket ID format
        run: |
          ticket_id=${{ inputs.ticket_id }}
          if [[ ! $ticket_id =~ ^(INC|CHG)[0-9]{10}$ ]]; then
            echo "Invalid ticket ID format. Must start with INC or CHG, followed by 10 digits."
            exit 1
          fi
          echo "Ticket ID format is valid."
      - name: "All pass"
        run: echo "All step pass for validation"
