name: test condition
on:
  workflow_dispatch:
    inputs:
      JAVA_VAR:
        type: string
        default: '11'
      COMMAND:
        type: string
      DEPLOY_COMMAND:
        type: string
jobs:
  build_jar:
    runs-on: mylab-vm
    name: building java code
    steps:
      - name: java build
        if: inputs.JAVA_VER <= 11 
        shell: bash
        run: |
          echo " I am building  java ${{ inputs.JAVA_VER }} with  ${{ inputs.COMMAND }}"
          if [ -z "${{ inputs.DEPLOY_COMMAND" }} ]; then
          echo "Another line has been given to deploy as ${{ inputs.DEPLOY_COMMAND }}"
          fi
      - name: java build 17
        if: inputs.JAVA_VER > 11
        shell: bash
        run: |          
          echo " I am building  java ${{ inputs.JAVA_VER }} with  ${{ inputs.COMMAND }}"
          if [ -z "${{ inputs.DEPLOY_COMMAND }}" ]; then
          echo "Another line has been given to deploy as ${{ inputs.DEPLOY_COMMAND }}"
          fi
