name: test condition
on:
  workflow_dispatch:
    inputs:
      JAVA_VER:
        type: number
        default: 11
      COMMAND:
        type: string
      DEPLOY_COMMAND:
        type: string
jobs:
  build_jar:
    runs-on: mylab-vm
    name: building java code
    steps:
      - name: java build
        shell: bash
        env:
          ART: developer
        run: |
          if [[ ${{ inputs.JAVA_VER }} -gt 11 ]]; then
          echo "Since you are using higher version of java than 11 so you can see me"
          fi
          echo " I am building  java ${{ inputs.JAVA_VER }} with  ${{ inputs.COMMAND }}"
          if [ "${{ inputs.DEPLOY_COMMAND }}" ]; then
          echo "ART=release" >> "$GITHUB_ENV"
          echo "Another line has been given to deploy as ${{ inputs.DEPLOY_COMMAND }}"
          fi
          env
        
