name: 'docker build'
on:
  workflow_call:
    inputs:
      msg1: 
        type: string
        default: "hello"
      msg2:
        type: string
        default: "vijay"
      LZ_ENVIRONMENT:
         description: 'LZ Environment'
         type: string
         default: "dev"

jobs:
  job2:
    runs-on: mylab-vm
    steps:
      - name: step1
        id: step1
        run: echo ${{ inputs.msg1 }}--${{ inputs.msg2 }}--${{ inputs.LZ_ENVIRONMENT }}
