name: workflow_1
on: [push, workflow_dispatch]
jobs:
  workflow1_job:
    runs-on: ubuntu-latest
    steps:
    - name: Set Output Variable
      id: my
      run: echo "myoutput=helloAll" >> "$GITHUB_OUTPUT"
    outputs:
      output1: ${{ steps.my.outputs.myoutput }}
