name: 'docker build'
on:
  workflow_call:
    inputs:
      msg1: 
        type: string
        default: "hello"
      msg2:
        type: string
        default: "vijay"
jobs:
  job2:
    runs-on: myvm-lab
    steps:
      - name: step1
        id: step1
        run: echo ${{ github.event.inputs.msg1 }}--${{ github.event.inputs.msg2 }}
