name: 'jar build'
on:
  workflow_call:
    outputs:
      msgout: 
        value: ${{ jobs.job1.outputs.output1 }}
jobs:
  job1:
    runs-on: mylab-vm
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - name: step1
        id: step1
        run: echo test=${{ github.run_number }}-${{ github.run_id }} >> $GITHUB_OUTPUT
